routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    // return view('welcome');
    //return view('layout.index');
    return view('login');
});

//Rutas controladores
Route::resource('C_User','Admin\UserController');

Route::get('user', function () {
    // return view('welcome');
    return view('admin.user');
});

Route::post('log', 'Admin\generalcontroller@log');
Route::resource('rol','Admin\RolController');

Route::resource('C_tipserv','Admin\tiposervController');
Route::resource('userespc','Admin\userespcController');

resources/views/admin/dashboard.blade.php
@extends('layout.index')

@section('content')


<h1>Prueba de oscar guacaneme esto es el dashboard</h1>


@stop

resources/views/admin/formrol.blade.php
@extends('layout.index')
@section('content')


<section class="content">
        <div class="card">
              <div class="card-header">
                <div class="">
                  <h3 class="card-title">Formulario de Tipo Servicios</h3>
                </div>
              </div>
  <!-- /.card-header -->
    <!-- /.card-body -->
              <div class="card-body">


                  <form class="form-horizontal" method="POST"   @if($Drol <> null) action="{{ route('rol.update',$Drol[0]->id) }}"  @else action="{{ route('rol.store') }}" @endif>
                    @csrf

                     @if($Drol <> null) @method('PUT') @endif


                    <input type="hidden" id="cod" name="cod" class="form-control is-warning" placeholder="..." value="@if($Drol<> null){{$Drol[0]->id}}@endif">

                      <div class="row">
                        <div class="col-sm-6">
                           <div class="form-group">
                             <label>Name</label>
                             <input type="text" id="Na" name="Na" class="form-control is-warning" placeholder="..." value="@if($Drol<> null){{$Drol[0]->name}}@endif">
                           </div>
                         </div>
                         <div class="col-sm-6">
                           <div class="form-group">
                             <label>level</label>
                             <input type="text" id="le" name="le" class="form-control is-warning" placeholder=" ..." value="@if($Drol<> null){{$Drol[0]->level}}@endif">
                           </div>
                         </div>
                      </div>

                      <div class="row">
                        <div class="col-sm-6">
                          <div class="form-group">
                          <button type="submit" class="btn btn-block btn-outline-primary" @if($Drol<> null) hidden @endif>Guardar</button>
                          </div>
                        </div>
                        <div class="col-sm-6">
                          <div class="form-group">
                            <button type="submit" class="btn btn-block btn-outline-secondary" @if($Drol == null) hidden @endif>Editar</button>
                          </div>
                        </div>
                      </div>
                  </form>


              </div>
          </div>
      <!-- /.card -->
    </section>

@endsection

resources/views/admin/formuser.blade.php
@extends('layout.index')
@section('content')


<section class="content">
        <div class="card">
              <div class="card-header">
                <div class="">
                  <h3 class="card-title">Formulario de Usuarios</h3>
                </div>
              </div>
  <!-- /.card-header -->
    <!-- /.card-body -->
              <div class="card-body">


                  <form class="form-horizontal" method="POST"   @if($DUser <> null) action="{{ route('C_User.update',$DUser[0]->id) }}"  @else action="{{ route('C_User.store') }}" @endif>
                    @csrf

                     @if($DUser <> null) @method('PUT')" @endif


                    <input type="hidden" id="id" name="id" class="form-control is-warning" placeholder="..." value="@if($DUser<> null){{$DUser[0]->id}}@endif">

                      <div class="row">
                        <div class="col-sm-6">
                           <div class="form-group">
                             <label>username</label>
                             <input type="text" id="name" name="name" class="form-control is-warning" placeholder="..." value="@if($DUser<> null){{$DUser[0]->username}}@endif">
                           </div>
                         </div>
                         <div class="col-sm-6">
                           <div class="form-group">
                             <label>status</label>
                             <input type="number" id="stat" name="stat" class="form-control is-warning" placeholder=" ..." value="@if($DUser<> null){{$DUser[0]->status}}@endif">
                           </div>
                         </div>
                      </div>

                      <div class="row">
                        <div class="col-sm-6">
                           <div class="form-group">
                             <label>Rol</label>
                             <select class="form-control" id="Idrol" name="Idrol">
                               @foreach($Drol as $rol)
                               <option value="{{$rol->id}}" >{{$rol->name}}</option>
                               @endforeach
                             </select>

                             </div>
                         </div>
                         <div class="col-sm-6">
                           <div class="form-group">
                             <label>Password</label>
                             <input type="password" id="pass" name="pass" class="form-control is-warning" placeholder=" ..." value="@if($DUser<> null){{$DUser[0]->password}}@endif">
                           </div>
                         </div>
                      </div>



                      <div class="row">
                        <div class="col-sm-6">
                          <div class="form-group">
                          <button type="submit" class="btn btn-block btn-outline-primary" @if($DUser<> null) hidden @endif>Guardar</button>
                          </div>
                        </div>
                        <div class="col-sm-6">
                          <div class="form-group">
                            <button type="submit" class="btn btn-block btn-outline-secondary" @if($DUser == null) hidden @endif>Editar</button>
                          </div>
                        </div>
                      </div>
                  </form>


              </div>
          </div>
      <!-- /.card -->
    </section>

@endsection

resources/views/admin/listrol.blade.php
@extends('layout.index')

@section('content')


  <div class="">
    <a href="{{route('rol.create')}}" class="btn btn-success">Nuevo</a>
  </div>
<section class="content">


  <div class="card">
       <div class="card-header">
            <h3 class="card-title">Listado Roles</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
        <!-- /.card-body -->
            <table  width="95%" cellpadding="0" cellspacing="0" border="0"  class="cell-border"   id="roles">
                <thead>
                       <tr>
                         <th>Id</th>
                         <th>Rol</th>
                         <th>Level</th>

                       </tr>
                </thead>
                <tbody>
                   @foreach($Rols as $Rol)
                       <tr>
                       <td>{{$Rol->id}}</td>
                       <td>{{$Rol->name}}</td>
                       <td>{{$Rol->level}}</td>
                       <td>
                         <a href="{{ route('rol.edit',$Rol->id) }}" class="fas fa-pen-fancy"></a>
                         {{-- <a href="{{ route('servclist.indexdet',$Rol->id) }}" class="fas fa-pen-fancy"></a> --}}
                         <a href="" class="fas fa-ban"></a>
                       {{-- <button class="ion ion-md-create" type="submit">Editar</button> --}}
                       </td>
                       </tr>
                   @endforeach
                </tbody>
            </table>

          </div>
    </div>
      <!-- /.card -->
    </section>
@stop

resources/views/admin/listuser.blade.php
@extends('layout.index')

@section('content')


  <div class="">
    <a href="{{route('C_User.create')}}" class="btn btn-success">Nuevo</a>
  </div>
<section class="content">


  <div class="card">
       <div class="card-header">
            <h3 class="card-title">Listado Usuarios</h3>
        </div>
        <!-- /.card-header -->
        <div class="card-body">
        <!-- /.card-body -->
            <table  width="95%" cellpadding="0" cellspacing="0" border="0"  class="cell-border"   id="usuarios">
                <thead>
                       <tr>
                         <th>Id</th>
                         <th>username</th>
                         <th>rol_id</th>
                         <th>status</th>
                         <th>Acción</th>
                       </tr>
                </thead>
                <tbody>
                   @foreach($Users as $detUsers)
                       <tr>
                       <td>{{$detUsers->id}}</td>
                       <td>{{$detUsers->username}}</td>
                       <td>{{$detUsers->rol_id}}</td>
                       <td>{{$detUsers->status}}</td>
                       <td>
                         <a href="{{ route('C_User.edit',$detUsers->id) }}" class="fas fa-pen-fancy"></a>
                         <a href="" class="fas fa-ban"></a>
                       {{-- <button class="ion ion-md-create" type="submit">Editar</button> --}}
                       </td>
                       </tr>
                   @endforeach
                </tbody>
            </table>

          </div>
    </div>
      <!-- /.card -->
    </section>
@stop